shared:
  image: node:14
jobs:
  main:
    requires: [ ~commit ]
    steps:
      - test: echo "test"
  success:
    requires: [ main ]
    steps:
      - sleep 10
      - test: echo "test"
  failure:
    requires: [ main ]
    steps:
      - test: exit 1
